#IMPORTANT: This is the latest version
app:
  name: jobs-backend-api
  version: 0.0.1-01-2024
#<><><><><><><><><><><><><><> HTTPS <><><><><><><><><><><><><><>
server:
  port: 8087
  http2:
    enabled: true
#<><><><><><><><><><><><><><> SPRING <><><><><><><><><><><><><><>
spring:
  config:
    import: optional:vault://PRX/jobs-backend/DEV
  application:
    name: ${app.name}
    description: Jobs Backend API
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  server:
    ssl:
      enabled: true
      bundle: config-server
  test:
    context:
      failure:
        threshold: 10000000
  #<><><><><><><><><><><><><><> SSL <><><><><><><><><><><><><><>
  ssl:
    bundle:
      jks:
        config-server:
          key:
            alias: prx.env-qa-docker
          keystore:
            location: classpath:prx.env-qa-docker.p12
            password: 13515030
            type: PKCS12
  #<><><><><><><><><><><><><><> CLOUD <><><><><><><><><><><><><><>
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
        - eth.*
        - lo
      preferredNetworks:
        - 172.18.0
  vault:
    enabled: true
    host: vault.qa.prx.test
    port: 8200
    backend: PRX
    uri: http://${spring.cloud.vault.host}:${spring.cloud.vault.port}
    authentication: token
    default-context: PRX/jobs-backend/dev
  output:
    ansi:
      enabled: DETECT
  #<><><><><><><><><><><><><><> JMX <><><><><><><><><><><><><><>
  jmx:
    default-domain: ${JMX_DEFAULT_DOMAIN}
  data:
    rest:
      base-path: /api
  #<><><><><><><><><><><><><><> DATABASES <><><><><><><><><><><><><><>
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    driver-class-name: org.postgresql.Driver
    #<><><><><><><><><><><><><><> CONNECTION POOL <><><><><><><><><><><><><><>
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      poolName: SpringBootJPAHikariCP-FinancialDataBridge
      idleTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 5
  #<><><><><><><><><><><><><><> PERSISTENCE <><><><><><><><><><><><><><>
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non_contextual_creation: true
    log-level: error
#<><><><><><><><><><><><><><> SERVICE DISCOVERY <><><><><><><><><><><><><><>
eureka:
  instance:
    home-page-url: ${EUREKA_HOME_PAGE_URL_PATH}
    preferIpAddress: true
    prefer-ip-address: true
    hostName: ${EUREKA_HOSTNAME}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    health-check-url: ${EUREKA_HEALTH_CHECK_URL_PATH}
    status-page-url-path: ${EUREKA_STATUS_PAGE_URL_PATH}
  client:
    healthcheck: true
    port: ${EUREKA_PORT}
    url: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
#<><><><><><><><><><><><><><> OPEN API <><><><><><><><><><><><><><>
swagger:
  base-package: 'com.prx.jobs.backend.v1'
api-info:
  title: ${app.name}
  description: ${app.description}
  contact:
    name: 'Luis Antonio Mata'
    url: 'www.prx.test'
    email: 'luis.antonio.mata@gmail.com'
  version: ${app.version}
springfox:
  documentation:
    swagger:
      enable: true
      v2:
        use-model-v3: true
    swagger-ui:
      base-url: /
springdoc:
  api-docs:
    path: /api-docs
