app:
  name: jobs-backend-api
  version: 0.0.1-01-2024
#<><><><><><><><><><><><><><> HTTPS <><><><><><><><><><><><><><>
server:
  port: 8183
  ssl:
    enabled: true
    bundle: config-server
#<><><><><><><><><><><><><><> SPRING <><><><><><><><><><><><><><>
spring:
  application:
    name: ${app.name}
    description: Jobs Backend API
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  server:
    port: ${server.port}
    ssl:
      enabled: true
      bundle: config-server
  #<><><><><><><><><><><><><><> SSL <><><><><><><><><><><><><><>
  ssl:
    bundle:
      jks:
        config-server:
          key:
            alias: ${SSL_JKS_CONFIG_SERVER_KEY_ALIAS}
          keystore:
            location: ${SSL_JKS_CONFIG_SERVER_KEYSTORE_LOCATION}
            password: ${SSL_JKS_CONFIG_SERVER_KEYSTORE_PASSWORD}
            type: ${SSL_JKS_CONFIG_SERVER_KEYSTORE_TYPE}
#<><><><><><><><><><><><><><> CLOUD <><><><><><><><><><><><><><>
cloud:
  discovery:
    enabled: true
  inetutils:
    ignoredInterfaces:
      - docker
      - eth.*
      - lo
    preferredNetworks:
      - 172.18.0
  output:
    ansi:
      enabled: DETECT
  #<><><><><><><><><><><><><><> JMX <><><><><><><><><><><><><><>
  jmx:
    default-domain: ${JMX_DEFAULT_DOMAIN}
    data:
      rest:
        base-path: /api
  # The Spring Cloud Config specific configurations
  #<><><><><><><><><><><><><><> VAULT <><><><><><><><><><><><><><>
  vault:
    token: ${VAULT_TOKEN}
    uri: ${VAULT_SERVER_URL}
    kv:
      backend: PRX
      default-context: ${app.name}
    application-name: ${app.name}
  bootstrap:
    # Enables the Spring Cloud Bootstrap application context
    enabled: ${SPRING_BOOT_CLOUD_BOOTSTRAP_ENABLED}
#<><><><><><><><><><><><><><> SERVICE DISCOVERY <><><><><><><><><><><><><><>
eureka:
  instance:
    home-page-url: ${EUREKA_HOME_PAGE_URL_PATH}
    preferIpAddress: true
    prefer-ip-address: true
    hostName: ${EUREKA_HOSTNAME}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    health-check-url: ${EUREKA_HEALTH_CHECK_URL_PATH}
    status-page-url-path: ${EUREKA_STATUS_PAGE_URL_PATH}
  client:
    healthcheck: true
    port: ${EUREKA_PORT}
    url: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

swagger:
  base-package: 'com.prx.jobs.backend.v1'
api-info:
  title: ${app.name}
  description: ${app.description}
  contact:
    name: 'Luis Antonio Mata'
    url: 'www.prx.test'
    email: 'luis.antonio.mata@gmail.com'
  version: ${app.version}
springfox:
  documentation:
    swagger:
      enable: true
      v2:
        use-model-v3: true
    swagger-ui:
      base-url: /

